# Site settings
title: Beth Goder
email: beth.goder@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Beth Goder worked as an archivist at Stanford before becoming a full-time writer and parent. Now she enjoys writing speculative fiction stories about archives, memory, records, and the relationship between the past and present.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bethgoder.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

paginate: 5

author:
  name: Beth Goder
  email: beth.goder@gmail.com

timezone: America/Los_Angeles
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

gems:
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-paginate
